### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by wlUnUlw** [HemantKArya/BloomeeTunes#25]
https://github.com/user-attachments/assets/bdf3bd2e-d81d-41bc-afdf-b4bb66a02361

No audio when played as you can see in this record. Both in YTM or YTV will act like that

**Comment by HemantKArya** [comment]
Hi, @wlUnUlw thanx you so much for reporting this issue/bug it seems pretty confusing cause I tried this in my current device it is working perfectly in all devices I have right now. So can you provide more details if you can like Android Version, Mobile Model/Version so that I or anyone else can try to figure it out that what could be the problem (assuming that YouTube music and Video is fully supported in that country.). And I will try to reproduce this bug in my device or emulators and try to figure it out 🙃.
https://github.com/user-attachments/assets/449d6873-0263-4f7c-9e18-1b85c2e85f25

**Comment by wlUnUlw** [comment]
I'm using Android 14, Oppo CPH2473

**Comment by HemantKArya** [comment]
okay I will look into that and try to reproduce this error in emulator or any device if I can find.

**Comment by wlUnUlw** [comment]
Uhhh,  somehow Bloomee in my device work normally today. I will try it for the next few days to see how it goes

**Comment by wlUnUlw** [comment]
Sorry for the confusion, it seem "Notification scheduling"  function in Regain cause it. 
![Screenshot_2024-08-24-22-08-56-55_b8f598334a8b3b69be3e76328e5ceaa8.jpg](https://github.com/user-attachments/assets/74e25704-a6df-40d2-88ab-f776e91ef12a)
But it kinda weird that only Bloomee encountered this situation, other music streaming apps still work fine with Regain. 

Anyway, thank for your support.
