### ISSUE TITLE
Bug: Music from YouTube will not load

### ISSUE THREAD

**Issue by SolidLamp** [HemantKArya/BloomeeTunes#51]
I get all music from YouTube. Until about 4 days ago, it was working fine. YouTube now just loads endlessly. It just shows the loading symbol and nothing happens. I have also tried a VPN and deleting the cache, but neither helped.

An update did not cause this issue; it just started happening. I thought it could be YouTube blocking by IP, but the YouTube app and website work fine, and a VPN does not fix this issue. I have also attached a screenshot of what is happening, but nothing is indicative of an issue. It just loads.

![Screenshot_2024-09-28-15-30-28-13_dafff40a4121cf68ccb459f939d7eea0.jpg](https://github.com/user-attachments/assets/9e9affb6-1e39-4077-9fba-001a9d86cc3a)

Android version: Android 11
Installation method: F-Droid (IzzyOnDroid), no root
Phone manufacturer: OPPO

P.S. This app is really nice

**Comment by HemantKArya** [comment]
Okay can you try to use the latest update from github since `izzyondroid`'s one will not update cause of versioning system is changed for f-droid compliance.
But if you already have saved items in your library then first take a backup in external directory using settings inside the app and then uninstall the app and reinstall from https://github.com/HemantKArya/BloomeeTunes/releases after that you easily restore backup from that file.
(It will something like bloomee_backup_db.isar)

**Comment by SolidLamp** [comment]
Thank you. With the update, it appears to be fixed. However, restoring the backup required that I assign the 'manage all files' permission to the app. This is likely a quirk with my manufacturer, though. Thank you again for your help.
