### ISSUE TITLE
[Bug] Spotify playlist import crashes

### ISSUE THREAD

**Issue by StaringLongingly** [HemantKArya/BloomeeTunes#6]
Steps to reproduce:

1. Try importing this playlist:
https://open.spotify.com/playlist/5dmRQJEzMUl42svLQq5jNR
Importer stops with an error at song #76

2. Try importing this playlist:
https://open.spotify.com/playlist/7gncJ6CduYUmucTcKV5VX7
Importer stops with an error at song #27

**Comment by HemantKArya** [comment]
thanks @StaringLongingly 🙏 for noticing this bug fixed it in 2.7.13 [41d60a2](https://github.com/HemantKArya/BloomeeTunes/commit/41d60a2760b3e2588ada2e97c15f274f8625ebb1). This problem is occurring cause the songs are not found in both platforms (with the same name in Spotify playlist) so now I think currently you have to find the song name manually in English or different so that it can appear in search results.
And as for this app we have to come with different way so that we can romanize any song name or artist name to make it easily discoverable in mixedAPI results.
